// Config for my External links
export const krish_resume = "Krish_Bharal - Resume.pdf";
export const chipmunk = "https://krish54491.github.io/Krish54491-chipmunk/";
export const pianowizards = "https://pianowizards.krish544.com";
// Config for games and tools - easily modifiable
export const GAMESNAV = [
  { label: "Tic-Tac-Toe", path: "/tictactoe" },
  { label: "Mouse Game", path: "/mouse" },
  { label: "Sideways Sam", path: "/sidewayssam" },
  { label: "Ultimate Tic-Tac-Toe", path: "/ultimatetictactoe" },
];

export const TOOLSNAV = [
  { label: "Countdown", path: "/countdown" },
  { label: "To-Do", path: "/todo" },
  { label: "Video Translator", path: "/videotranslator" },
  { label: "Video Rater", path: "/videorater" },
  { label: "Base Converter", path: "/baseconverter" },
];
export const map: Map<number, string> = new Map([
  [0, "0"],
  [1, "1"],
  [2, "2"],
  [3, "3"],
  [4, "4"],
  [5, "5"],
  [6, "6"],
  [7, "7"],
  [8, "8"],
  [9, "9"],
  [10, "A"],
  [11, "B"],
  [12, "C"],
  [13, "D"],
  [14, "E"],
  [15, "F"],
  [16, "G"],
  [17, "H"],
  [18, "I"],
  [19, "J"],
  [20, "K"],
  [21, "L"],
  [22, "M"],
  [23, "N"],
  [24, "O"],
  [25, "P"],
  [26, "Q"],
  [27, "R"],
  [28, "S"],
  [29, "T"],
  [30, "U"],
  [31, "V"],
  [32, "W"],
  [33, "X"],
  [34, "Y"],
  [35, "Z"],
  [36, "a"],
  [37, "b"],
  [38, "c"],
  [39, "d"],
  [40, "e"],
  [41, "f"],
  [42, "g"],
  [43, "h"],
  [44, "i"],
  [45, "j"],
  [46, "k"],
  [47, "l"],
  [48, "m"],
  [49, "n"],
  [50, "o"],
  [51, "p"],
  [52, "q"],
  [53, "r"],
  [54, "s"],
  [55, "t"],
  [56, "u"],
  [57, "v"],
  [58, "w"],
  [59, "x"],
  [60, "y"],
  [61, "z"],
  [62, "Α"],
  [63, "Β"],
  [64, "Γ"],
  [65, "Δ"],
  [66, "Ε"],
  [67, "Ζ"],
  [68, "Η"],
  [69, "Θ"],
  [70, "Ι"],
  [71, "Κ"],
  [72, "Λ"],
  [73, "Μ"],
  [74, "Ν"],
  [75, "Ξ"],
  [76, "Ο"],
  [77, "Π"],
  [78, "Ρ"],
  [79, "Σ"],
  [80, "Τ"],
  [81, "Υ"],
  [82, "Φ"],
  [83, "Χ"],
  [84, "Ψ"],
  [85, "Ω"],
  [86, "α"],
  [87, "β"],
  [88, "γ"],
  [89, "δ"],
  [90, "ε"],
  [91, "ζ"],
  [92, "η"],
  [93, "θ"],
  [94, "ι"],
  [95, "κ"],
  [96, "λ"],
  [97, "μ"],
  [98, "ν"],
  [99, "ξ"],
  [100, "ο"],
  [101, "π"],
  [102, "ρ"],
  [103, "ς"],
  [104, "τ"],
  [105, "υ"],
  [106, "φ"],
  [107, "χ"],
  [108, "ψ"],
  [109, "ω"],
]);
export const reverseMap: Map<string, number> = new Map(
  [...map.entries()].map(([key, value]) => [value, key]),
);
export const dropdownSpacing = 5;
export const baseOptions = Array.from({ length: 109 }, (_, i) => i + 2);
export const NO_COMMENTS_PAGES = [
  // only the core pages shouldn't have comments I'll have to implement this in the backend as well each time it's updated
  "/",
  "/login",
  "/account",
  "/register",
  "/games",
  "/tools",
  "/projects",
];
export const CONTACT_INFO = "krishbharal@gmail.com";
export const socialLinks = [
  {
    name: "LinkedIn",
    icon: "linkedin",
    href: "https://www.linkedin.com/in/krish-bharal-389105296/",
  },
  { name: "GitHub", icon: "github", href: "https://github.com/Krish54491" },
  // {
  //   name: "Instagram",
  //   icon: "instagram",
  //   href: "#",
  // },
  {
    name: "YouTube",
    icon: "youtube",
    href: "https://www.youtube.com/@krish544_was_stolen",
  },
  // { name: "Discord", icon: "discord", href: "#" },
];
